### ISSUE TITLE
ClassNotFoundException from PlayMessages$SpawnEntity using latest Neoforge

### ISSUE THREAD

**Issue by zjedi** [henkelmax/corpse#180]
### Bug description

The mod causes latest Neoforge to crash.

### Minecraft version

1.20.4

### Mod version

1.0.9

### Mod loader and version

NeoForge 20.4.170

### Steps to reproduce

Install mod, start launcher -> crash.

```
Caused by: java.lang.ClassNotFoundException: net.neoforged.neoforge.network.PlayMessages$SpawnEntity
		at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:197) ~[securejarhandler-2.1.24.jar:?] {}
		at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?] {}
		at de.maxhenkel.corpse.Main.lambda$createCorpseEntityType$4(Main.java:124) ~[corpse-neoforge-1.20.4-1.0.9.jar%23179!/:1.20.4-1.0.9] {re:classloading}


### Expected behavior

The mods loads without crashing Neoforge launcher

### Log files

https://gist.github.com/zjedi/8afda53a8415ce19248e57ef3a846a81

### Screenshots

_No response_

**Comment by henkelmax** [comment]
You are using an outdated mod version!
